export const fields = {
  salesforce: [
    {
      id: "customer_key",
      name: "customer_key",
      type: "text",
      placeholder: "Enter customer key",
      label: "Customer key",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "customer_secret",
      name: "customer_secret",
      type: "text",
      placeholder: "Enter customer secret",
      label: "Customer secret",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "domain",
      name: "domain",
      type: "text",
      placeholder: "Enter domain",
      label: "Domain",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
  ],
  zoho: [
    {
      id: "client_id",
      name: "client_id",
      type: "text",
      placeholder: "Enter client id",
      label: "Client id",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "client_secret",
      name: "client_secret",
      type: "text",
      placeholder: "Enter client secret",
      label: "Client secret",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "generated_code",
      name: "generated_code",
      type: "text",
      placeholder: "Enter generated code",
      label: "Generated code",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
  ],
  hubspot: [
    {
      id: "access_token",
      name: "access_token",
      type: "text",
      placeholder: "Enter access token",
      label: "Access token",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
  ],
  monday: [
    {
      id: "api_key",
      name: "api_key",
      type: "text",
      placeholder: "Enter api key",
      label: "Api key",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "board_id",
      name: "board_id",
      type: "text",
      placeholder: "Enter board ID",
      label: "Board ID  ",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "email_id",
      name: "email_id",
      type: "text",
      placeholder: "Enter email ID",
      label: "Email ID ",
      isInput: true,
      isRequired: false,
      isReadOnly: false,
    },
  ],
  kommo: [
    {
      id: "access_token",
      name: "access_token",
      type: "text",
      placeholder: "Enter access token",
      label: "Access token",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "domain",
      name: "domain",
      type: "text",
      placeholder: "Enter domain",
      label: "Domain",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
  ],
  teamleader: [
    {
      id: "name",
      name: "name",
      type: "text",
      placeholder: "Enter integration name",
      label: "Integration name",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "client_id",
      name: "client_id",
      type: "text",
      placeholder: "Enter client id",
      label: "Client id",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "client_secret",
      name: "client_secret",
      type: "text",
      placeholder: "Enter client secret",
      label: "Client secret",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "generated_code",
      name: "generated_code",
      type: "text",
      placeholder: "Enter generated code",
      label: "Generated code",
      isInput: true,
      isRequired: true,
      isReadOnly: true,
    },
  ],
};

export const titles = {
  salesforce: "Salesforce",
  zoho: "Zoho CRM",
  hubspot: "HubSpot",
  monday: "Monday Sales",
  kommo: "Kommo",
  teamleader: "Teamleader",
};

export const tutorials = {
  salesforce:
    "https://video.wixstatic.com/video/9e7c89_3f3adb4d7bd44a059259f343a0b2ff8e/1080p/mp4/file.mp4",
  zoho: "https://video.wixstatic.com/video/9e7c89_106b35abce2e4e30b90b142b00d6fe40/1080p/mp4/file.mp4",
  hubspot:
    "https://video.wixstatic.com/video/9e7c89_3a89069420164ca290087f0ce9905d7f/1080p/mp4/file.mp4",
  monday:
    "https://video.wixstatic.com/video/9e7c89_f694c5f8b49a47be93aafcb409e76e0c/1080p/mp4/file.mp4",
  kommo:
    "https://video.wixstatic.com/video/9e7c89_25d2a95422474fcfae390eca73fd8ae8/1080p/mp4/file.mp4",
  teamleader:
    "https://video.wixstatic.com/video/9e7c89_3b727f9830564b97bf10b567700316ec/1080p/mp4/file.mp4",
};
