export const fields = {
  salesforce: [
    {
      id: "customer_key",
      name: "customer_key",
      type: "text",
      placeholder: "Enter customer key",
      label: "Customer key",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "customer_secret",
      name: "customer_secret",
      type: "text",
      placeholder: "Enter customer secret",
      label: "Customer secret",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "domain",
      name: "domain",
      type: "text",
      placeholder: "Enter domain",
      label: "Domain",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
  ],
  zoho: [
    {
      id: "client_id",
      name: "client_id",
      type: "text",
      placeholder: "Enter client id",
      label: "Client id",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "client_secret",
      name: "client_secret",
      type: "text",
      placeholder: "Enter client secret",
      label: "Client secret",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "generated_code",
      name: "generated_code",
      type: "text",
      placeholder: "Enter generated code",
      label: "Generated code",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
  ],
  hubspot: [
    {
      id: "access_token",
      name: "access_token",
      type: "text",
      placeholder: "Enter access token",
      label: "Access token",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
  ],
  monday: [
    {
      id: "api_key",
      name: "api_key",
      type: "text",
      placeholder: "Enter api key",
      label: "Api key",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "board_id",
      name: "board_id",
      type: "text",
      placeholder: "Enter board ID",
      label: "Board ID  ",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
  ],
  kommo: [
    {
      id: "access_token",
      name: "access_token",
      type: "text",
      placeholder: "Enter access token",
      label: "Access token",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "domain",
      name: "domain",
      type: "text",
      placeholder: "Enter domain",
      label: "Domain",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
  ],
  teamleader: [
    {
      id: "name",
      name: "name",
      type: "text",
      placeholder: "Enter integration name",
      label: "Integration name",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "client_id",
      name: "client_id",
      type: "text",
      placeholder: "Enter client id",
      label: "Client id",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "client_secret",
      name: "client_secret",
      type: "text",
      placeholder: "Enter client secret",
      label: "Client secret",
      isInput: true,
      isRequired: true,
      isReadOnly: false,
    },
    {
      id: "generated_code",
      name: "generated_code",
      type: "text",
      placeholder: "Enter generated code",
      label: "Generated code",
      isInput: true,
      isRequired: true,
      isReadOnly: true,
    },
  ],
};
