export const fieldsListings = [
  {
    id: "price",
    name: "price",
    type: "number",
    placeholder: "Enter price",
    label: "Price",
    isInput: true,
    isRequired: true,
    isReadOnly: false,
  },
  {
    id: "bed",
    name: "bed",
    type: "number",
    placeholder: "Enter bed",
    label: "Bed",
    isInput: true,
    isRequired: true,
    isReadOnly: false,
  },
  {
    id: "size",
    name: "size",
    type: "number",
    placeholder: "Enter Sq Ft",
    label: "Sq Ft",
    isInput: true,
    isRequired: true,
    isReadOnly: false,
  },
  {
    id: "bath",
    name: "bath",
    type: "number",
    placeholder: "Enter bath",
    label: "Bath",
    isInput: true,
    isRequired: true,
    isReadOnly: false,
  },
  {
    id: "annual_tax",
    name: "annual_tax",
    type: "number",
    placeholder: "Enter est. annual tax",
    label: "Annual tax",
    isInput: true,
    isRequired: true,
    isReadOnly: false,
  },
  {
    id: "types",
    name: "types",
    placeholder: "Enter your location types",
    label: "Location types",
    isInput: false,
    isRequired: true,
    isReadOnly: false,
    options: [
      { value: "houses-for-sales", label: "Houses for Sales" },
      { value: "sold-houses", label: "Sold Houses" },
      { value: "open-houses", label: "Open Houses" },
      { value: "pending-houses", label: "Pending Houses" },
    ],
  },
  {
    id: "year_built",
    name: "year_built",
    type: "number",
    placeholder: "Enter year built",
    label: "Year built",
    isInput: true,
    isRequired: true,
    isReadOnly: false,
  },
];

export const schemaLocation = {
  id: null,
  address: null,
  place_id: null,
  price: null,
  bed: null,
  bath: null,
  size: null,
  description: null,
  year_built: null,
  annual_tax: null,
  types: null,
  company_id: null,
  home_types: [],
  images: {
    img_1: null,
    img_2: null,
    img_3: null,
    img_4: null,
    img_5: null,
    img_6: null,
    img_7: null,
  },
};
